apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: todo-repo
  namespace: flux
spec:
  interval: 10m
  url: https://github.com/LosBlancos4/DevOps-with-Kubernetes.git
  ref:
    branch: main